packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

autoInstallPeers: false
disallowWorkspaceCycles: true
engineStrict: true
failIfNoMatch: true
linkWorkspacePackages: false
nodeVersion: 24.20.0
pmOnFail: error
preferWorkspacePackages: false
runtimeOnFail: error
savePrefix: "="
saveWorkspaceProtocol: rolling
sharedWorkspaceLockfile: true
strictPeerDependencies: true
