[package]
name = "landfall-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []

[dependencies]
landfall-core.workspace = true
landfall-observer.workspace = true
landfall-protocol.workspace = true
landfall-report.workspace = true
landfall-storage.workspace = true

[lints]
workspace = true
